# Copyright 2026 Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from datetime import date

# List of packages for PCL wildcard matches.
PCL_DEPS = ["pcl"]

# List of BCR packages for Qt5 matches
QT5_DEPS = ["rules_qt"]

# List of BCR packages for Qt6 matches
QT6_DEPS = ["rules_qt"]

# List of BCR packages for Python matches
PYTHON_DEPS = [
    "rules_python",
    "aspect_rules_py",
]

# List of BCR packages for Boost matches
BOOST_DEPS = [
    "boost.algorithm",
    "boost.align",
    "boost.any",
    "boost.array",
    "boost.asio",
    "boost.assert",
    "boost.assign",
    "boost.atomic",
    "boost.beast",
    "boost.bimap",
    "boost.bind",
    "boost.callable_traits",
    "boost.charconv",
    "boost.chrono",
    "boost.circular_buffer",
    "boost.compat",
    "boost.compatibility",
    "boost.compute",
    "boost.concept_check",
    "boost.config",
    "boost.container",
    "boost.container_hash",
    "boost.context",
    "boost.conversion",
    "boost.core",
    "boost.coroutine",
    "boost.coroutine2",
    "boost.crc",
    "boost.date_time",
    "boost.describe",
    "boost.detail",
    "boost.dll",
    "boost.dynamic_bitset",
    "boost.endian",
    "boost.exception",
    "boost.filesystem",
    "boost.foreach",
    "boost.format",
    "boost.function",
    "boost.functional",
    "boost.function_types",
    "boost.fusion",
    "boost.geometry",
    "boost.graph",
    "boost.hash2",
    "boost.heap",
    "boost.hof",
    "boost.icl",
    "boost.integer",
    "boost.interprocess",
    "boost.intrusive",
    "boost.io",
    "boost.iostreams",
    "boost.iterator",
    "boost.json",
    "boost.lambda",
    "boost.lambda2",
    "boost.leaf",
    "boost.lexical_cast",
    "boost.locale",
    "boost.lockfree",
    "boost.log",
    "boost.logic",
    "boost.math",
    "boost.move",
    "boost.mp11",
    "boost.mpl",
    "boost.mqtt5",
    "boost.multi_array",
    "boost.multi_index",
    "boost.multiprecision",
    "boost.mysql",
    "boost.numeric_conversion",
    "boost.numeric_interval",
    "boost.numeric_ublas",
    "boost.optional",
    "boost.parameter",
    "boost.pfr",
    "boost.phoenix",
    "boost.pin_version",
    "boost.polygon",
    "boost.pool",
    "boost.predef",
    "boost.preprocessor",
    "boost.process",
    "boost.program_options",
    "boost.property_map",
    "boost.property_tree",
    "boost.proto",
    "boost.ptr_container",
    "boost.python",
    "boost.qvm",
    "boost.random",
    "boost.range",
    "boost.ratio",
    "boost.rational",
    "boost.regex",
    "boost.scope",
    "boost.scope_exit",
    "boost.serialization",
    "boost.signals2",
    "boost.smart_ptr",
    "boost.sort",
    "boost.spirit",
    "boost.stacktrace",
    "boost.static_assert",
    "boost.static_string",
    "boost.system",
    "boost.test",
    "boost.thread",
    "boost.throw_exception",
    "boost.timer",
    "boost.tokenizer",
    "boost.tti",
    "boost.tuple",
    "boost.type_index",
    "boost.typeof",
    "boost.type_traits",
    "boost.units",
    "boost.unordered",
    "boost.url",
    "boost.utility",
    "boost.uuid",
    "boost.variant",
    "boost.variant2",
    "boost.vmd",
    "boost.winapi",
    "boost.xpressive",
]

# Ros package to BCR module name mapping for external dependencies.
ROS_TO_BAZEL_MAPPING = {
    "acado_vendor": None,
    "acl": None,
    "action_tutorials_interfaces": None,
    "actionlib_msgs": None,
    "ads_vendor": None,
    "ament_cmake_vendor_package": None,
    "asio": ["asio"],
    "assimp-dev" : ["assimp"],
    "assimp" : ["assimp"],
    "autoconf": ["rules_autoconf"],
    "automake": ["rules_foreign_cc"],
    "aws_sdk_cpp_vendor": None,
    "aws_sdk_vendor": ["aws_sdk"],
    "benchmark": None,
    "binutils": None,
    "black": None,
    "boost_sml_vendor": None,
    "bullet": ["bullet"],
    "bzip2": ["bzip2"],
    "cargo": ["rules_rust"],
    "catch2": ["catch2"],
    "clang-format": None,
    "clang-tidy": None,
    "clang": None,
    "cli11": ["cli11"],
    "clips_vendor": None,
    "cmake": None,
    "coinor-libipopt-dev": None,
    "console_bridge_vendor": ["console_bridge"],
    "cppcheck": None,
    "curl": ["curl"],
    "cwiid-dev": None,
    "cwiid": None,
    "dkms": None,
    "doxygen": ["rules_doxygen"],
    "dpkg": None,
    "eigen": ["eigen"],
    "fastcdr": ["fastcdr"],
    "fastdds": ["fastdds"],
    "ffmpeg-dev" : ["ffmpeg"],
    "ffmpeg" : ["ffmpeg"],
    "file": ["libmagic"],
    "fmilibrary_vendor": None,
    "fmt": ["fmt"],
    "foonathan_memory_vendor": None,
    "gazebo_ros_pkgs": None,
    "gdal": None,
    "geographiclib-tools": ["geographiclib"],
    "geographiclib": ["geographiclib"],
    "geos": None,
    "git": ["git"],
    "glslang-dev" : None,
    "glslang-dev": None,
    "glslc" : None,
    "glut": None,
    "gmock_vendor": ["googletest"],
    "google_benchmark_vendor": ["google_benchmark"],
    "google-mock": ["googletest"],
    "graphviz": None,
    "gtest_vendor": ["googletest"],
    "gtest": ["googletest"],
    "gurumdds-3.2": None,
    "gz_cmake_vendor": None,
    "gz_common_vendor": ["gz-common"],
    "gz_dartsim_vendor": ["dartsim"],
    "gz_fuel_tools_vendor": ["gz-fuel-tools"],
    "gz_gui_vendor": None,
    "gz_launch_vendor": None,
    "gz_math_vendor": ["gz-math"],
    "gz_msgs_vendor": ["gz-msgs"],
    "gz_ogre_next_vendor": ["ogre-next"],
    "gz_physics_vendor": ["gz-physics"],
    "gz_plugin_vendor": ["gz-plugin"],
    "gz_rendering_vendor": ["gz-rendering"],
    "gz_sensors_vendor": ["gz-sensors"],
    "gz_sim_vendor": ["gz-sim"],
    "gz_tools_vendor": None,
    "gz_transport_vendor": ["gz-transport"],
    "gz_utils_vendor": ["gz-utils"],
    "hash_library_vendor": None,
    "hdf5-tools" : None,
    "iwyu": None,
    "jupyter-notebook": None,
    "lcov": ["lcov"],
    "libabsl-dev": ["abseil-cpp"],
    "libatomic": None,
    "libavahi-client-dev": None,
    "libavdevice-dev": None,
    "libbluetooth-dev": None,
    "libbluetooth": None,
    "libc++-dev" : None,
    "libcaer_vendor": None,
    "libcairo2-dev": ["cairo"],
    "libcap-dev": ["libcap"],
    "libccd-dev": ["ccd"],
    "libceres-dev": ["ceres-solver"],
    "libclang-dev": None,
    "libconsole-bridge-dev": ["console_bridge"],
    "libcurl_vendor": ["curl"],
    "libcurl-dev": ["curl"],
    "libdbus-dev": None,
    "libdraco-dev": None,
    "libdw-dev": None,
    "libdwarf-dev" : ["libdwarf"],
    "libepoxy-dev": None,
    "libfcl-dev": ["fcl"],
    "libfcl": ["fcl"],
    "libflann-dev": ["flann"],
    "libfreeimage-dev": ["freeimage"],
    "libfreenect-dev": None,
    "libfreetype-dev" : ["freetype"],
    "libfreetype6" : ["freetype"],
    "libgdal-dev": None,
    "libgeos++-dev": None,
    "libgflags-dev": ["gflags"],
    "libglew-dev": ["glew"],
    "libglfw3-dev": ["glfw"],
    "libgoogle-glog-dev": ["glog"],
    "libgps": None,
    "libgsl" : ["gsl"],
    "libgstreamer-plugins-base1.0-dev": None,
    "libgstreamer1.0-dev": None,
    "libhdf5-dev" : None,
    "libicu-dev": ["icu"],
    "libjpeg": ["libjpeg_turbo"],
    "libjson-c-dev": None,
    "libjsoncpp-dev": ["jsoncpp"],
    "libjsoncpp": ["jsoncpp"],
    "liblapack-dev": None,
    "liblttng-ctl-dev": ["lttng-ust"],
    "liblttng-ust-dev": ["lttng-ust"],
    "liblz4_vendor": ["lz4"],
    "liblz4-dev" : ["lz4"],
    "liblz4" : ["lz4"],
    "libmodbus-dev": ["libmodbus"],
    "libncurses-dev": ["ncurses"],
    "libnlopt-cxx-dev": ["nlopt"],
    "liboctomap-dev": ["octomap"],
    "libogg": ["ogg"],
    "libogre-dev" : ["ogre-next"],
    "libomp-dev": None,
    "libopenblas-dev" : None,
    "libopencv-dev": ["opencv"],
    "libopencv-imgproc-dev": ["opencv"],
    "libopenni2-dev": None,
    "libopenscenegraph" : None,
    "liborocos-kdl-dev": None,
    "liborocos-kdl": None,
    "libpaho-mqtt-dev": ["paho.mqtt.cpp"],
    "libpaho-mqttpp-dev": ["paho.mqtt.cpp"],
    "libpcap-dev": ["libpcap"],
    "libpcap": ["libpcap"],
    "libpcl-all-dev": ["pcl"],
    "libpng-dev": ["libpng"],
    "libpoco-dev": ["poco"],
    "libqhull": ["qhull"],
    "libqwt-qt5-dev": None,
    "libserial-dev": None,
    "libshaderc-dev" : None,
    "libspnav-dev": None,
    "libsqlite3-dev": ["sqlite3"],
    "libssl-dev": ["openssl"],
    "libtheora": None,
    "libtins-dev": None,
    "libtool": None,
    "libturbojpeg": ["libjpeg_turbo"],
    "libudev-dev": None,
    "liburdfdom-dev": ["urdfdom"],
    "liburdfdom-headers-dev": ["urdfdom_headers"],
    "liburdfdom-tools": ["urdfdom"],
    "libusb-1.0-dev": ["libusb"],
    "libusb-1.0": ["libusb"],
    "libusb-dev": ["libusb"],
    "libusb" : ["libusb"],
    "libv4l-dev": None,
    "libvulkan-dev" : ["rules_vulkan"],
    "libwebsocketpp-dev": ["websocketpp"],
    "libwebsockets-dev": ["libwebsockets"],
    "libx11-dev": ["libx11"],
    "libx11-xcb-dev" : ["libxcb"],
    "libx11": ["libx11"],
    "libxaw" : None,
    "libxcb-randr0-dev" : ["libxcb"],
    "libxcursor-dev" : ["libxcursor"],
    "libxi-dev": ["libxi"],
    "libxinerama-dev" : ["libxinerama"],
    "libxkbcommon-dev": ["xkbcommon"],
    "libxml2-utils": ["libxml2"],
    "libxml2": ["libxml2"],
    "libxmlrpc-c++": None,
    "libxmu-dev": None,
    "libxrandr": ["libxrandr"],
    "libxxf86vm": None,
    "libyaml_vendor": ["libyaml"],
    "libyaml-dev": ["libyaml"],
    "libyaml" : ["libyaml"],
    "libyuv-dev": None,
    "libzip-dev": ["zip"],
    "libzmq3-dev": ["libzmq"],
    "libzstd-dev": ["zstd"],
    "live555_vendor": None,
    "lm-sensors": None,
    "lttng-tools": ["lttng-ust"],
    "lua-dev": ["lua"],
    "lua5.2-dev": ["lua"],
    "lz4_vendor": ["lz4"],
    "lz4": ["lz4"],
    "magic_enum": ["magic_enum"],
    "matio": None,
    "mcap_vendor": ["mcap"],
    "menge_vendor": None,
    "meson": ["meson"],
    "mimick_vendor": ["mimick"],
    "mp_units_vendor": ["mp-units"],
    "mujoco_vendor": None,
    "muparser": None,
    "nanobind-dev": ["nanobind"],
    "nlohmann_json_schema_validator_vendor": None,
    "nlohmann-json-dev": ["nlohmann_json"],
    "ocl-icd-opencl-dev": None,
    "omp": None,
    "open3d_vendor": None,
    "opencl-headers": None,
    "opende": None,
    "openeb_vendor": None,
    "opengl": None,
    "openssl": ["openssl"],
    "orocos_kdl_vendor": None,
    "ortools_vendor": None,
    "osqp_vendor": None,
    "pkg-config": None,
    "proj": None,
    "protobuf-dev": ["protobuf"],
    "protobuf": ["protobuf"],
    "pugixml-dev": ["pugixml"],
    "pugixml": ["pugixml"],
    "pybind11_json_vendor": None,
    "pybind11_vendor": ["pybind11_bazel"],
    "pybind11-dev": ["pybind11_bazel"],
    "pybind11-json-dev": None,
    "pydocstyle": None,
    "pyflakes3": None,
    "python_orocos_kdl_vendor": None,
    "python-argparse": None,
    "python3": None,
    "qml-module-qtquick2": None,
    "qml6-module-qt-labs-folderlistmodel" : None,
    "qml6-module-qt-labs-platform" : None,
    "qml6-module-qt-labs-settings" : None,
    "qml6-module-qt5compat-graphicaleffects" : None,
    "qml6-module-qtcharts" : None,
    "qml6-module-qtcore" : None,
    "qml6-module-qtpositioning" : None,
    "qml6-module-qtqml-models" : None,
    "qml6-module-qtqml-workerscript": None,
    "qml6-module-qtqml" : None,
    "qml6-module-qtquick-controls" : None,
    "qml6-module-qtquick-dialogs" : None,
    "qml6-module-qtquick-layouts" : None,
    "qml6-module-qtquick-templates" : None,
    "qml6-module-qtquick-window" : None,
    "qml6-module-qtquick": None,
    "qpoases_vendor": None,
    "range-v3": ["range-v3"],
    "rapidjson-dev": ["rapidjson"],
    "ros_ign_bridge": None,
    "ros_ign_gazebo": None,
    "rti-connext-dds-7.3.0": None,
    "ruby": ["rules_ruby"],
    "rviz_ogre_vendor": None,
    "sdformat_vendor": ["sdformat"],
    "sdl2_vendor": ["sdl2"],
    "sdl2": ["sdl2"],
    "simde": ["simde"],
    "socat": None,
    "sol_vendor": None,
    "spacenavd": None,
    "spdlog_vendor": ["spdlog"],
    "spdlog": ["spdlog"],
    "spirv-headers" : ["spirv_headers"],
    "spirv-tools" : ["spirv_headers"],
    "sqlite3_vendor": ["sqlite3"],
    "sqlite3": ["sqlite3"],
    "subversion" : None,
    "suitesparse": ["suitesparse"],
    "swig": ["swig"],
    "tango_icons_vendor": None,
    "tango-icon-theme" : None,
    "tbb": ["onetbb"],
    "tinyspline_vendor": None,
    "tinyxml_vendor": ["tinyxml"],
    "tinyxml" : ["tinyxml"],
    "tinyxml2_vendor": ["tinyxml2"],
    "tinyxml2": ["tinyxml2"],
    "tvm_vendor": None,
    "udev": None,
    "uncrustify_vendor": None,
    "uncrustify" : None,
    "unzip" : ["zip"],
    "uuid": ["libuuid"],
    "v4l-utils": None,
    "wayland-dev": ["wayland"],
    "wayland": ["wayland"],
    "wget": None,
    "wx-common": None,
    "wxwidgets": None,
    "xacro": ["xacro"],
    "xclip": None,
    "xvfb": None,
    "yaml_cpp_vendor": ["yaml-cpp"],
    "yaml-cpp": ["yaml-cpp"],
    "yaml": ["libyaml"],
    "zbar": None,
    "zenoh_cpp_vendor": ["zenoh-cpp"],
    "zlib": ["zlib"],
    "zmqpp_vendor": None,
    "zstd_vendor": ["zstd"],
    "zziplib" : None,
}

def get_copyright_header():
    return """# Copyright {0} Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.\n
""".format(date.today().year)