# Copyright 2026 Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module(
    name = "rcr-examples",
    version = "rolling.2026-04-15.rcr.1",
)

# BCR dependencies for this package

bazel_dep(name = "aspect_rules_py", version = "1.11.2")
bazel_dep(name = "protobuf", version = "35.0-rc1")
bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "rules_python", version = "1.9.0")
bazel_dep(name = "rules_rs", version = "0.0.56")
bazel_dep(name = "rules_rust", version = "0.69.0")
bazel_dep(name = "llvm", version = "0.8.6")

## RCR deps

# Load the release
bazel_dep(name = "ros", version = "rolling.2026-04-15.rcr.1")

# Make the following packages visible to this project.
bazel_dep(name = "rclc", version="0.0.0")
bazel_dep(name = "rclcpp", version="0.0.0")
bazel_dep(name = "rclpy", version="0.0.0")
bazel_dep(name = "rosidl_generator_c", version="0.0.0")
bazel_dep(name = "rosidl_generator_cpp", version="0.0.0")
bazel_dep(name = "rosidl_generator_py", version="0.0.0")
bazel_dep(name = "rosidl_generator_rs", version="0.0.0")
bazel_dep(name = "sensor_msgs", version="0.0.0")

## BOOTSTRAP

# Register our hermetic compiler (clang)
register_toolchains("@llvm//toolchain:all")

# Python / pip

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.12",
)

pip_ros = use_extension("@rosdistro//python:defs.bzl", "pip_ros")
use_repo(pip_ros, "pip_ros")

# Rust / crates

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2021",
    versions = ["1.85.0"],
)
