# Copyright 2026 Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@aspect_rules_py//py:defs.bzl", _py_test = "py_test")

# py_pytest (below) is a public macro any RCR package can call, so its pytest
# dependency must resolve against whatever Python version the *consuming*
# workspace actually selected -- not a hardcoded hub. requirement() can't be
# imported dynamically (load() is static), so we import it from every
# supported hub under a version-specific name and select() on rules_python's
# public is_python_X.Y config settings at the bottom of this file.
load("@pip_311//:requirements.bzl", requirement_3_11 = "requirement")
load("@pip_312//:requirements.bzl", requirement_3_12 = "requirement")

# The Python versions rosdistro registers a toolchain + pip.parse() hub for.
# Keep in sync with the python.toolchain()/pip.parse() calls in MODULE.bazel,
# and with the load()s and _PYTEST_REQUIREMENT select() above/below.
_SUPPORTED_PYTHON_VERSIONS = ["3.11", "3.12"]
_DEFAULT_PYTHON_VERSION = "3.12"

_PYTEST_REQUIREMENT = select({
    "@rules_python//python/config_settings:is_python_3.11": [requirement_3_11("pytest")],
    "//conditions:default": [requirement_3_12("pytest")],
})

def _hub_apparent_name(python_version):
    return "pip_" + python_version.replace(".", "")

def _pip_ros_proxy_impl(rctx):
    """Create a pip_ros proxy repo that forwards to the real pip_ros hub.

    The real pip_ros hub is created by the pip extension in rosdistro's MODULE.bazel.
    This extension creates a proxy repository visible to rosdistro's dependent modules.
    """

    # The canonical name of the real pip_ros hub (@@rules_python++pip+pip_ros).
    # We use the canonical @@-prefixed form to avoid the proxy resolving @pip_ros
    # back to itself and causing a cycle.
    real_hub = rctx.attr.real_hub_canonical_name

    rctx.file("BUILD.bazel", """\
package(default_visibility = ["//visibility:public"])

# Ensure the `requirements.bzl` source can be accessed, since users load() from it.
exports_files(["requirements.bzl"])
""")

    # Write a requirements.bzl that re-exports everything from the real pip_ros hub
    # using its canonical @@-prefixed name to avoid self-reference cycles.
    rctx.file("requirements.bzl", """\
\"\"\"Forwarding requirements.bzl for pip_ros.

This proxy re-exports the pip_ros hub created by the rosdistro module.
@generated by rosdistro pip_ros module extension.
\"\"\"

load("@@{real_hub}//:requirements.bzl",
     _all_requirements = "all_requirements",
     _all_whl_requirements_by_package = "all_whl_requirements_by_package",
     _all_whl_requirements = "all_whl_requirements",
     _all_data_requirements = "all_data_requirements",
     _requirement = "requirement",
     _whl_requirement = "whl_requirement",
     _data_requirement = "data_requirement",
     _dist_info_requirement = "dist_info_requirement",
)

all_requirements = _all_requirements
all_whl_requirements_by_package = _all_whl_requirements_by_package
all_whl_requirements = _all_whl_requirements
all_data_requirements = _all_data_requirements

def requirement(name):
    return _requirement(name)

def whl_requirement(name):
    return _whl_requirement(name)

def data_requirement(name):
    return _data_requirement(name)

def dist_info_requirement(name):
    return _dist_info_requirement(name)
""".format(real_hub = real_hub))

_pip_ros_proxy = repository_rule(
    implementation = _pip_ros_proxy_impl,
    attrs = {
        "real_hub_canonical_name": attr.string(
            mandatory = True,
            doc = "The canonical repository name of the real pip_ros hub (without @@ prefix).",
        ),
    },
    doc = """A proxy repository that exposes the pip_ros hub to dependent modules.

This is an internal rule used by the pip_ros module extension.
""",
)

_toolchain = tag_class(
    doc = """Select which rosdistro Python version to expose as @pip_ros.

Only honored when called from the root module (mirrors how rules_python's own
`python.toolchain(is_default = True, ...)` is root-only). If omitted, or
called only from a non-root module, rosdistro exposes its default version's
hub ({default}).
""".format(default = _DEFAULT_PYTHON_VERSION),
    attrs = {
        "python_version": attr.string(
            default = _DEFAULT_PYTHON_VERSION,
            doc = "One of rosdistro's supported Python versions: {}.".format(
                ", ".join(_SUPPORTED_PYTHON_VERSIONS),
            ),
        ),
    },
)

def _pip_ros_impl(module_ctx):
    python_version = _DEFAULT_PYTHON_VERSION
    for mod in module_ctx.modules:
        if not mod.is_root:
            continue
        for tag in mod.tags.toolchain:
            python_version = tag.python_version

    if python_version not in _SUPPORTED_PYTHON_VERSIONS:
        fail((
            "pip_ros.toolchain(python_version = \"{version}\") is not " +
            "supported by rosdistro. Supported versions: {supported}."
        ).format(
            version = python_version,
            supported = ", ".join(_SUPPORTED_PYTHON_VERSIONS),
        ))

    # Find the canonical name of the real pip_ros hub for the selected
    # version. Each hub is created by the pip extension and is visible to
    # rosdistro (where this extension is hosted) under a version-specific
    # apparent name (e.g. "pip_312"); we get its canonical name via
    # repo_mapping so the proxy below can reference it unambiguously.
    hub_apparent_name = _hub_apparent_name(python_version)
    real_hub_canonical = str(Label("@" + hub_apparent_name + "//:_")).split("//")[0].lstrip("@")

    # Create a pip_ros proxy repository that dependent modules can use_repo().
    _pip_ros_proxy(
        name = "pip_ros",
        real_hub_canonical_name = real_hub_canonical,
    )

# This extension exposes one of rosdistro's pip hubs to dependent modules,
# selected by Python version. Dependent modules should use:
#   pip_ros = use_extension("@rosdistro//python:defs.bzl", "pip_ros")
#   pip_ros.toolchain(python_version = "3.11")  # optional, defaults to 3.12
#   use_repo(pip_ros, "pip_ros")
pip_ros = module_extension(
    implementation = _pip_ros_impl,
    tag_classes = {
        "toolchain": _toolchain,
    },
)

# Macro for pytest invocations.
def py_pytest(name, srcs, deps = [], args = [], **kwargs):
    _py_test(
        name = name,
        main = "@rosdistro//python:pytest_main.py",
        srcs = srcs + [
            "@rosdistro//python:pytest_main.py",
        ],
        deps = deps + _PYTEST_REQUIREMENT,
        args = args + [
            "$(location :%s)" % s
            for s in srcs
        ],
        **kwargs
    )
