# Copyright 2025 Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# We strongly advise that any project that uses the ROS Central Registry
# declares itself as a module. Even though bazel's naming allows for
# more flexibility you should only use lower-case characters and
# underscores, per REP-0144 (https://ros.org/reps/rep-0144.html).

module(
    name = "rcr-docs",
    bazel_compatibility = [">=7.2.1"],
)

# BCR dependencies

bazel_dep(name = "aspect_rules_py", version = "1.11.7")
bazel_dep(name = "rules_python", version = "2.2.0")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    is_default = True,
    python_version = "3.11",
)

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "pip_ros_central_registry",
    python_version = "3.11",
    requirements_lock = "//:requirements.txt",
)
use_repo(pip, "pip_ros_central_registry")
