# Copyright 2025 Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: build-and-test
run-name: Build and test across multiple operating systems, architectures and Bazel versions.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  # This avoids building anything that wouldn't merge.
  lint-bazel-files:
    name: Run buildifier on all Bazel files
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Run Buildifier
      uses: buildbuddy-io/buildifier-action@v1.0.0
      with:
        mode: check
        warnings: "all"

  # Only try and build if linting passes.
  checkout-setup-build-test:
    needs: lint-bazel-files

    permissions:
      actions: read
      checks: write
      contents: read
      id-token: write  # needed for Google Cloud auth
      
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: 'ubuntu-24.04_bazel-8.5.1_x86_64',  os: 'ubuntu-24.04',     bazel-version: '8.5.1' }
          - { name: 'ubuntu-24.04_bazel-9.0.0_x86_64',  os: 'ubuntu-24.04',     bazel-version: '9.0.0' }
          - { name: 'ubuntu-24.04_bazel-8.5.1_aarch64', os: 'ubuntu-24.04-arm', bazel-version: '8.5.1' }
          - { name: 'ubuntu-24.04_bazel-9.0.0_aarch64', os: 'ubuntu-24.04-arm', bazel-version: '9.0.0' }
    steps:

    # Remove unnecessary files to maximize build space.
    - name: Free disk space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    # Checkout this repository and all submodules.
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Authenticate with Google Cloud
    - name: Authenticate to Google Cloud
      uses: "google-github-actions/auth@71fee32a0bb7e97b4d33d548e7d957010649d8fa"
      with:
        workload_identity_provider: projects/771457463613/locations/global/workloadIdentityPools/github-automation/providers/build-dev
        service_account: github-automation-bot@gha-intrinsic-opensource-rcr.iam.gserviceaccount.com
        create_credentials_file: true

    # Setup bazel as a tool for building.
    - name: Setup Bazel
      uses: bazel-contrib/setup-bazel@0.15.0

    # Build the ROS examples.
    - name: Build code
      env:
        USE_BAZEL_VERSION: ${{ matrix.bazel-version }}
      run: bazel build --config=ci

    # Test the distribution.
    - name: Run tests
      env:
        USE_BAZEL_VERSION: ${{ matrix.bazel-version }}
      run: bazel test --config=ci --jobs 1

    # Summarize the results.
    - name: Test report
      uses: dorny/test-reporter@v2
      with:
        name: Bazel tests
        path: bazel-testlogs/**/test.xml
        reporter: java-junit
      if: always()

    # Upload test test logs
    - name: Upload test logs
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }} (test logs)
        path: "bazel-testlogs/**/test.log"
      if: always()

    # Create badges for each build
    - name: Update status badges
      uses: Schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.STATUS_BADGE_SECRET }}
        gistID: 4d05b2382879fbd51f9a07bb7c63fb29
        filename: ${{ matrix.name }}.json
        label: ${{ matrix.name }}
        message: ${{ job.status == 'success' && 'pass' || 'fail' }}
        color: ${{ job.status == 'success' && 'green' || 'red' }}
      if: github.ref_name == 'main'
