# Copyright 2026 Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: check_distribution
run-name: Perform a build across platforms, bazel versions and variants.
env:
  ANDROID_HOME: ""
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  checkout-setup-build-test:
    permissions:
      actions: read
      checks: write
      contents: read
      id-token: write
    name: ${{ matrix.ros }}_${{ matrix.variant }}_${{ matrix.bazel }}_${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: workspace
    env:
      USE_BAZEL_VERSION: ${{ matrix.bazel }}
    strategy:
      fail-fast: false
      matrix:
        bazel:
        - 8.x
        - 9.x
        ros:
        - lyrical.2026-06-08.rcr.1
        variant:
        - perception
        os:
        - ubuntu-26.04
        - ubuntu-26.04-arm
        - macos-26-intel
        - macos-26
    steps:
    - name: Free disk space
      if: runner.os == 'Linux'
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - name: Checkout repository and submodules
      uses: actions/checkout@v7
      with:
        fetch-depth: 0
    - name: Authenticate to Google Cloud
      uses: "google-github-actions/auth@71fee32a0bb7e97b4d33d548e7d957010649d8fa"
      with:
        workload_identity_provider: projects/771457463613/locations/global/workloadIdentityPools/github-automation/providers/build-dev
        service_account: github-automation-bot@gha-intrinsic-opensource-rcr.iam.gserviceaccount.com
        create_credentials_file: true
    - name: Setup Bazel
      uses: bazel-contrib/setup-bazel@0.19.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}
        repository-cache: false
    - name: Prepare workspace
      id: prepare_workspace
      working-directory: .
      run: |
        bazel run //tools/ci:setup_workspace -- --release ${{ matrix.ros }}
    - name: Build
      id: build
      run: |
        bazel build --config ci --config=${{ matrix.variant }}
    - name: Test (rmw_fastrtps_cpp)
      continue-on-error: true
      id: test_rmw_fastrtps_cpp
      run: |
        bazel test --config ci --config=${{ matrix.variant }} --test_env=RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    - name: Test (rmw_fastrtps_dynamic_cpp)
      id: test_rmw_fastrtps_dynamic_cpp
      continue-on-error: true
      run: |
        bazel test --config ci --config=${{ matrix.variant }} --test_env=RMW_IMPLEMENTATION=rmw_fastrtps_dynamic_cpp
    - name: Test (rmw_cyclonedds_cpp)
      id: test_rmw_cyclonedds_cpp
      continue-on-error: true
      run: |
        bazel test --config ci --config=${{ matrix.variant }} --test_env=RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    - name: Test (rmw_zenoh_cpp)
      id: test_rmw_zenoh_cpp
      continue-on-error: true
      run: |
        bazel run @rmw_zenoh_cpp//:rmw_zenohd 2>zenohd-stderr.log 1>zenohd-stdout.log &
        trap "pkill -f rmw_zenohd 2>/dev/null || true" EXIT
        bazel test --config ci --config=${{ matrix.variant }} --test_env=RMW_IMPLEMENTATION=rmw_zenoh_cpp
